INSERT INTO funds (code, isin_class, name, fund_type, risk_level, annual_mgmt_fee, benchmark_index, market_focus, min_investment) VALUES
('SI-MM-01', 'CLASS D-ACC',    'Smart Invest Global Money Funds - Hong Kong Dollar',           'MONEY_MARKET',  1, 0.0031, NULL,                                          'Hong Kong Money Market instruments',            100.00),
('SI-BI-01', 'CLASS HC-HKD-ACC', 'Smart Invest Global Aggregate Bond Index Fund',              'BOND_INDEX',    1, 0.0025, 'Bloomberg Global Aggregate Bond Index',        'Global investment-grade bonds',               100.00),
('SI-BI-02', 'CLASS HC-HKD-ACC', 'Smart Invest Global Corporate Bond Index Fund',              'BOND_INDEX',    2, 0.0031, 'Bloomberg Global Corporate Bond Index',        'Global investment-grade corporates',          100.00),
('SI-EI-01', 'CLASS HC-HKD-ACC', 'Smart Invest US Equity Index Fund',                        'EQUITY_INDEX',  4, 0.0031, 'S&P 500 Net Total Return Index',               'US domestic market — NYSE and NASDAQ top 500', 100.00),
('SI-EI-02', 'CLASS HC-HKD-ACC', 'Smart Invest Global Equity Index Fund',                    'EQUITY_INDEX',  4, 0.0040, 'MSCI World Index',                             'Global developed markets',                    100.00),
('SI-EI-03', 'CLASS HC-HKD-ACC', 'Smart Invest Hang Seng Index Fund',                        'EQUITY_INDEX',  5, 0.0050, 'Hang Seng Index',                              'Hong Kong equity market',                    100.00),
('SI-MA-01', 'CLASS BC-HKD-ACC', 'Smart Invest Portfolios - World Selection 1 (Conservative)','MULTI_ASSET',  1, 0.0060, NULL,                                          'Diversified conservative multi-asset',        100.00),
('SI-MA-02', 'CLASS BC-HKD-ACC', 'Smart Invest Portfolios - World Selection 2 (Moderately Conservative)','MULTI_ASSET',2, 0.0060, NULL,                                  'Diversified moderately conservative multi-asset',100.00),
('SI-MA-03', 'CLASS BC-HKD-ACC', 'Smart Invest Portfolios - World Selection 3 (Balanced)',   'MULTI_ASSET',  3, 0.0060, NULL,                                          'Diversified balanced multi-asset',            100.00),
('SI-MA-04', 'CLASS BC-HKD-ACC', 'Smart Invest Portfolios - World Selection 4 (Adventurous)','MULTI_ASSET',  4, 0.0060, NULL,                                          'Diversified medium-to-high risk multi-asset', 100.00),
('SI-MA-05', 'CLASS BC-HKD-ACC', 'Smart Invest Portfolios - World Selection 5 (Speculative)','MULTI_ASSET',  5, 0.0060, NULL,                                          'Diversified high-risk multi-asset',          100.00);
